### ISSUE TITLE
Visuals of CLI output not good!

### ISSUE THREAD

**Issue by naryal2580** [Goron1606/TokenBreaker#1]
# Dear Goron, 
## The visuals of output or the results are not so good.

**Comment by cyberblackhole** [comment]
Ok naryal, I'll try to make the visuals better. Let me what do you like to change in it.

**Comment by naryal2580** [comment]
# Dear Goron,
## I have already forked your project. I'll make the visuals way better. And, also remove the dependency of *huepy*.

**Comment by cyberblackhole** [comment]
Thanks @naryal2580 for code contribution.
